### ISSUE TITLE
Richard voit pas l'animation (et je le sais que vous avez fait exprès !)

### ISSUE THREAD

**Issue by plumpaiok** [RobertJam/manpac#10]
@patzy @IamKazuya @mlg05 
![c_po_juste](https://cloud.githubusercontent.com/assets/6865291/13555757/162baa7a-e3c9-11e5-99cd-f8de8c40cabe.PNG)

Plize ailpe.

**Comment by alexisLefebvre** [comment]
:smile:

**Comment by patzy** [comment]
j'ai le meme bug sur mon portable avec la carte intel.
A priori je dirais image trop grand (13000 et qques de largeur sur 57 de haut).
Faut rendre ca plus carré, a priori la limite max est de 8192 pixels sur ce genre de carte

**Comment by alexisLefebvre** [comment]
En redécoupant le gros sprite en plusieurs sprites ça le ferait ? Par exemple en séparant les animations de marche, etc. C'est jouable ou trop compliqué de charger plusieurs fichiers de sprite ?

**Comment by patzy** [comment]
il suffit de redecouper le fichier pour qu'il soit sur plusieurs 'lignes' plutot qu'une seule enorme ligne

**Comment by alexisLefebvre** [comment]
@plumpaiok Tu vois les animations maintenant ?
