### ISSUE TITLE
Intégrer des polices

### ISSUE THREAD

**Issue by alexisLefebvre** [RobertJam/manpac#6]
Cf. https://github.com/KennyShields/LoveFrames/wiki/The-Text-Object > `setFont()`.

Appliquer la police à tout le jeu.

**Comment by alexisLefebvre** [comment]
Reçu 5 sur 5 @plumpaiok. :)

**Comment by alexisLefebvre** [comment]
Récupérer la police dans le dépôt Graphisme: https://github.com/RobertJam/Graphisme

**Comment by alexislefebvre** [comment]
Intégration de police : https://www.reddit.com/r/love2d/comments/3tsgl3/loveframes_issue_fonts_dont_reload_on_reloading/

**Comment by alexisLefebvre** [comment]
Documentation : https://love2d.org/wiki/love.graphics.newFont

**Comment by alexisLefebvre** [comment]
Il n'y a pas de fonction `setFont` pour définir la police d'un bouton : https://github.com/KennyShields/LoveFrames/wiki/The-Button-Object

**Comment by alexisLefebvre** [comment]
Pour définir une police de façon globale il faudrait quelque chose comme ça : https://www.reddit.com/r/love2d/comments/3tsgl3/loveframes_issue_fonts_dont_reload_on_reloading/
