### ISSUE TITLE
Créer de quoi paramétrer les parties

### ISSUE THREAD

**Issue by plumpaiok** [RobertJam/manpac#9]
@patzy  @IamKazuya 
Pour tester et équilibrer.
Que ça se fasse par interface à la création de partie, ou par un fichier de paramètres à modifier.
paramètres listés sur ce Framapad -> https://bimestriel.framapad.org/p/Game_Concept_Robert_Jam

**Comment by patzy** [comment]
en place, reste a ajouter dautres parametres
